"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, KeyRound, Loader2, Mail, ShieldCheck, Sprout } from "lucide-react";
import { toast } from "sonner";
import { z } from "zod";
import { apiPost } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { InputOTP, InputOTPGroup, InputOTPSlot } from "@/components/ui/input-otp";
import { PasswordInput } from "@/components/farm/PasswordInput";
import { cn } from "@/lib/utils";

const STEPS=[{key:"request",label:"Email"},{key:"verify",label:"Verify"},{key:"reset",label:"New password"}];
export default function ResetPasswordPage(){
 const [step,setStep]=useState("request"),[email,setEmail]=useState(""),[code,setCode]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[busy,setBusy]=useState(false),[cooldown,setCooldown]=useState(0);
 useEffect(()=>{if(cooldown<=0)return;const t=setTimeout(()=>setCooldown(c=>c-1),1000);return()=>clearTimeout(t)},[cooldown]);
 async function sendCode(e){e?.preventDefault();const p=z.string().trim().email("Enter a valid email address").max(255).safeParse(email);if(!p.success){toast.error(p.error.issues[0].message);return}setBusy(true);try{await apiPost("/accounts/otp/request/",{email:p.data});setStep("verify");setCooldown(45);toast.success("If the account exists, a verification code is on its way.")}catch(err){toast.error(err.message||"Could not send the verification code")}finally{setBusy(false)}}
 async function verify(e){e.preventDefault();if(code.length!==6){toast.error("Enter the 6-digit code from your email");return}setBusy(true);try{await apiPost("/accounts/otp/verify/",{email,code});setStep("reset");toast.success("Code verified. Choose a new password.")}catch(err){toast.error(err.message||"That code is invalid or expired.")}finally{setBusy(false)}}
 async function updatePassword(e){e.preventDefault();const p=z.string().min(8,"Use at least 8 characters").max(72).safeParse(password);if(!p.success){toast.error(p.error.issues[0].message);return}if(password!==confirm){toast.error("Passwords do not match");return}setBusy(true);try{await apiPost("/accounts/password-reset/confirm/",{password});setStep("done");toast.success("Password reset successfully.")}catch(err){toast.error(err.message||"Could not reset your password")}finally{setBusy(false)}}
 const activeIndex=STEPS.findIndex(s=>s.key===step);
 return <main className="grid min-h-screen place-items-center bg-background grain-field px-5 py-10"><div className="w-full max-w-sm"><Link href="/" className="mb-6 flex items-center gap-2.5"><span className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground"><Sprout className="size-5"/></span><span className="font-display text-sm font-semibold">FarmPulse</span></Link><div className="rounded-2xl border border-border/70 bg-card/80 p-6 backdrop-blur-sm">
 {step!=="done"&&<div className="mb-6 flex items-center gap-2">{STEPS.map((s,i)=><div key={s.key} className="flex flex-1 items-center gap-2"><span className={cn("grid size-6 shrink-0 place-items-center rounded-full font-mono text-[11px]",i<=activeIndex?"bg-primary text-primary-foreground":"border border-border text-muted-foreground")}>{i+1}</span><span className={cn("truncate text-[11px]",i===activeIndex?"text-foreground":"text-muted-foreground")}>{s.label}</span>{i<STEPS.length-1&&<span className="h-px flex-1 bg-border"/>}</div>)}</div>}
 {step==="request"&&<form onSubmit={sendCode} className="space-y-4"><span className="grid size-10 place-items-center rounded-xl bg-primary/15 text-primary"><Mail className="size-5"/></span><div><h1 className="font-display text-xl font-semibold">Forgot your password?</h1><p className="mt-1 text-sm text-muted-foreground">Enter your account email and we’ll send a one-time 6-digit code.</p></div><div className="space-y-1.5"><Label htmlFor="email">Email</Label><Input id="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@farm.co" required/></div><Button className="w-full" disabled={busy}>{busy?<Loader2 className="size-4 animate-spin"/>:null}Send verification code</Button><Link href="/login" className="flex items-center justify-center gap-1.5 text-xs text-muted-foreground hover:text-foreground"><ArrowLeft className="size-3.5"/>Back to sign in</Link></form>}
 {step==="verify"&&<form onSubmit={verify} className="space-y-4"><span className="grid size-10 place-items-center rounded-xl bg-primary/15 text-primary"><ShieldCheck className="size-5"/></span><div><h1 className="font-display text-xl font-semibold">Enter your code</h1><p className="mt-1 text-sm text-muted-foreground">We sent a 6-digit code to <span className="text-foreground">{email}</span>. It expires in 10 minutes.</p></div><div className="flex justify-center py-1"><InputOTP maxLength={6} value={code} onChange={setCode}><InputOTPGroup>{[0,1,2,3,4,5].map(i=><InputOTPSlot key={i} index={i}/>)}</InputOTPGroup></InputOTP></div><Button className="w-full" disabled={busy}>{busy?<Loader2 className="size-4 animate-spin"/>:null}Verify code</Button><div className="flex items-center justify-between text-xs"><button type="button" onClick={()=>setStep("request")} className="text-muted-foreground hover:text-foreground">Change email</button><button type="button" disabled={cooldown>0||busy} onClick={()=>sendCode()} className="text-primary disabled:text-muted-foreground">{cooldown>0?`Resend in ${cooldown}s`:"Resend code"}</button></div></form>}
 {step==="reset"&&<form onSubmit={updatePassword} className="space-y-4"><span className="grid size-10 place-items-center rounded-xl bg-primary/15 text-primary"><KeyRound className="size-5"/></span><div><h1 className="font-display text-xl font-semibold">Choose a new password</h1><p className="mt-1 text-sm text-muted-foreground">Use at least 8 characters.</p></div><div className="space-y-1.5"><Label htmlFor="np">New password</Label><PasswordInput id="np" value={password} onChange={setPassword} required/></div><div className="space-y-1.5"><Label htmlFor="cp">Confirm password</Label><PasswordInput id="cp" value={confirm} onChange={setConfirm} required/></div><Button className="w-full" disabled={busy}>{busy?<Loader2 className="size-4 animate-spin"/>:null}Reset password</Button></form>}
 {step==="done"&&<div className="space-y-4 text-center"><span className="mx-auto grid size-10 place-items-center rounded-xl bg-primary/15 text-primary">✓</span><div><h1 className="font-display text-xl font-semibold">Password updated</h1><p className="mt-1 text-sm text-muted-foreground">Your password has been changed successfully.</p></div><Button className="w-full" onClick={()=>window.location.href="/login"}>Return to sign in</Button></div>}
 </div></div></main>
}
